"""SHAP explainability utilities for the churn prediction model."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import joblib
import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shap

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.preprocessing.data_loader import load_customer_data
from src.preprocessing.preprocess import (
    DEFAULT_DATA_PATH,
    clean_telco_dataframe,
    split_features_target,
    transform_to_dataframe,
)
from src.training.train_model import DEFAULT_BEST_MODEL_PATH


DEFAULT_SHAP_OUTPUT_DIR = PROJECT_ROOT / "outputs" / "shap"
DEFAULT_SUMMARY_PLOT_PATH = DEFAULT_SHAP_OUTPUT_DIR / "shap_summary.png"
DEFAULT_FEATURE_IMPORTANCE_PATH = DEFAULT_SHAP_OUTPUT_DIR / "shap_feature_importance.png"
DEFAULT_WATERFALL_PLOT_PATH = DEFAULT_SHAP_OUTPUT_DIR / "shap_waterfall.png"
DEFAULT_PREDICTION_EXPLANATION_PATH = DEFAULT_SHAP_OUTPUT_DIR / "prediction_explanation.json"
DEFAULT_PREDICTION_EXPLANATION_CSV_PATH = DEFAULT_SHAP_OUTPUT_DIR / "prediction_explanation_features.csv"
DEFAULT_PREDICTION_EXPLANATION_MD_PATH = DEFAULT_SHAP_OUTPUT_DIR / "prediction_explanation.md"


@dataclass(frozen=True)
class ExplainabilityData:
    """Prepared data needed for SHAP explainability."""

    raw_data: pd.DataFrame
    raw_features: pd.DataFrame
    transformed_features: pd.DataFrame
    target: pd.Series


@dataclass(frozen=True)
class ShapArtifacts:
    """Files generated by the SHAP explainability workflow."""

    summary_plot_path: Path
    feature_importance_plot_path: Path
    waterfall_plot_path: Path
    prediction_explanation_path: Path
    prediction_explanation_csv_path: Path
    prediction_explanation_md_path: Path
    selected_row_index: int
    selected_customer_id: str | None
    predicted_probability: float
    predicted_label: str


def load_model_bundle(model_path: str | Path = DEFAULT_BEST_MODEL_PATH) -> dict[str, Any]:
    """Load the trained model bundle saved by the training pipeline."""
    return joblib.load(model_path)


def prepare_explainability_data(
    model_bundle: dict[str, Any],
    data_path: str | Path = DEFAULT_DATA_PATH,
) -> ExplainabilityData:
    """Load, clean, and transform raw data for SHAP explanations."""
    raw_data = load_customer_data(data_path)
    cleaned_data = clean_telco_dataframe(raw_data)
    raw_features, target = split_features_target(cleaned_data)
    transformed_features = transform_to_dataframe(
        model_bundle["preprocessing_pipeline"],
        raw_features,
        index=raw_features.index,
    )

    return ExplainabilityData(
        raw_data=cleaned_data,
        raw_features=raw_features,
        transformed_features=transformed_features,
        target=target,
    )


def sample_background(
    transformed_features: pd.DataFrame,
    *,
    background_size: int = 200,
    random_state: int = 42,
) -> pd.DataFrame:
    """Create a representative background sample for SHAP."""
    if len(transformed_features) <= background_size:
        return transformed_features

    return shap.sample(transformed_features, background_size, random_state=random_state)


def sample_explanation_rows(
    transformed_features: pd.DataFrame,
    *,
    max_explain_rows: int = 1000,
    random_state: int = 42,
) -> pd.DataFrame:
    """Sample rows used for summary and feature-importance plots."""
    if len(transformed_features) <= max_explain_rows:
        return transformed_features

    return transformed_features.sample(max_explain_rows, random_state=random_state).sort_index()


def build_shap_explainer(model: Any, background: pd.DataFrame) -> shap.Explainer:
    """Build a SHAP explainer for the fitted model."""
    return shap.Explainer(model, background)


def to_positive_class_explanation(explanation: shap.Explanation) -> shap.Explanation:
    """Normalize binary-class SHAP output to the positive churn class."""
    values = np.asarray(explanation.values)
    base_values = np.asarray(explanation.base_values)

    if values.ndim == 3:
        positive_class_index = 1 if values.shape[-1] > 1 else 0
        values = values[:, :, positive_class_index]

        if base_values.ndim == 2:
            base_values = base_values[:, positive_class_index]

        return shap.Explanation(
            values=values,
            base_values=base_values,
            data=explanation.data,
            feature_names=explanation.feature_names,
        )

    return explanation


def compute_shap_values(
    model: Any,
    transformed_features: pd.DataFrame,
    *,
    background_size: int = 200,
    max_explain_rows: int = 1000,
    random_state: int = 42,
) -> tuple[shap.Explainer, shap.Explanation, pd.DataFrame]:
    """Compute SHAP values for sampled rows."""
    background = sample_background(
        transformed_features,
        background_size=background_size,
        random_state=random_state,
    )
    rows_to_explain = sample_explanation_rows(
        transformed_features,
        max_explain_rows=max_explain_rows,
        random_state=random_state,
    )
    explainer = build_shap_explainer(model, background)
    explanation = to_positive_class_explanation(explainer(rows_to_explain))

    return explainer, explanation, rows_to_explain


def save_summary_plot(
    explanation: shap.Explanation,
    features: pd.DataFrame,
    output_path: str | Path = DEFAULT_SUMMARY_PLOT_PATH,
    *,
    max_display: int = 20,
) -> Path:
    """Save a SHAP summary beeswarm plot."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    plt.close("all")
    shap.summary_plot(
        explanation.values,
        features=features,
        feature_names=list(features.columns),
        max_display=max_display,
        show=False,
    )
    plt.tight_layout()
    plt.savefig(path, dpi=180, bbox_inches="tight")
    plt.close("all")

    return path


def save_feature_importance_plot(
    explanation: shap.Explanation,
    features: pd.DataFrame,
    output_path: str | Path = DEFAULT_FEATURE_IMPORTANCE_PATH,
    *,
    max_display: int = 20,
) -> Path:
    """Save a SHAP mean absolute feature-importance plot."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    plt.close("all")
    shap.summary_plot(
        explanation.values,
        features=features,
        feature_names=list(features.columns),
        plot_type="bar",
        max_display=max_display,
        show=False,
    )
    plt.tight_layout()
    plt.savefig(path, dpi=180, bbox_inches="tight")
    plt.close("all")

    return path


def choose_prediction_row(
    model: Any,
    transformed_features: pd.DataFrame,
    *,
    row_index: int | None = None,
    customer_id: str | None = None,
    raw_data: pd.DataFrame | None = None,
) -> int:
    """Select a row for individual prediction explanation.

    If no row or customer ID is provided, the highest predicted churn-risk row
    is selected to produce a useful waterfall explanation.
    """
    if customer_id is not None:
        if raw_data is None or "customerID" not in raw_data.columns:
            raise ValueError("customer_id lookup requires raw data with a customerID column.")

        matches = raw_data.index[raw_data["customerID"].astype(str).eq(str(customer_id))].tolist()
        if not matches:
            raise ValueError(f"Customer ID '{customer_id}' was not found.")
        return int(matches[0])

    if row_index is not None:
        if row_index not in transformed_features.index:
            raise ValueError(f"Row index {row_index} was not found in transformed features.")
        return int(row_index)

    probabilities = model.predict_proba(transformed_features)[:, 1]
    highest_risk_position = int(np.argmax(probabilities))
    return int(transformed_features.index[highest_risk_position])


def save_waterfall_plot(
    explainer: shap.Explainer,
    transformed_features: pd.DataFrame,
    row_index: int,
    output_path: str | Path = DEFAULT_WATERFALL_PLOT_PATH,
    *,
    max_display: int = 15,
) -> tuple[Path, shap.Explanation]:
    """Save a SHAP waterfall plot for one prediction."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    row = transformed_features.loc[[row_index]]
    row_explanation = to_positive_class_explanation(explainer(row))

    plt.close("all")
    shap.plots.waterfall(row_explanation[0], max_display=max_display, show=False)
    plt.tight_layout()
    plt.savefig(path, dpi=180, bbox_inches="tight")
    plt.close("all")

    return path, row_explanation[0]


def build_prediction_explanation(
    model_bundle: dict[str, Any],
    explainability_data: ExplainabilityData,
    row_index: int,
    row_explanation: shap.Explanation,
    *,
    top_n: int = 10,
) -> tuple[dict[str, Any], pd.DataFrame]:
    """Create a structured prediction explanation for one customer."""
    model = model_bundle["model"]
    transformed_row = explainability_data.transformed_features.loc[[row_index]]
    probability = float(model.predict_proba(transformed_row)[0, 1])
    predicted_class = int(model.predict(transformed_row)[0])
    target_classes = model_bundle.get("target_classes", ["No", "Yes"])
    predicted_label = str(target_classes[predicted_class])

    shap_values = np.asarray(row_explanation.values, dtype=float)
    feature_names = list(row_explanation.feature_names)
    feature_values = transformed_row.iloc[0].to_dict()

    feature_contributions = pd.DataFrame(
        {
            "feature": feature_names,
            "transformed_value": [feature_values[feature] for feature in feature_names],
            "shap_value": shap_values,
            "absolute_shap_value": np.abs(shap_values),
            "direction": np.where(shap_values >= 0, "increases churn risk", "decreases churn risk"),
        }
    ).sort_values("absolute_shap_value", ascending=False)

    raw_record = explainability_data.raw_data.loc[row_index]
    customer_id = raw_record.get("customerID") if "customerID" in raw_record.index else None
    key_fields = [
        "customerID",
        "Contract",
        "tenure",
        "MonthlyCharges",
        "TotalCharges",
        "InternetService",
        "PaymentMethod",
        "TechSupport",
        "OnlineSecurity",
        "Churn",
    ]
    raw_context = {
        field: _json_safe(raw_record[field])
        for field in key_fields
        if field in raw_record.index
    }

    top_features = feature_contributions.head(top_n)
    positive_features = (
        feature_contributions[feature_contributions["shap_value"] > 0]
        .head(top_n)
        .to_dict(orient="records")
    )
    negative_features = (
        feature_contributions[feature_contributions["shap_value"] < 0]
        .head(top_n)
        .to_dict(orient="records")
    )

    base_value = float(np.asarray(row_explanation.base_values).reshape(-1)[0])
    shap_sum = float(base_value + shap_values.sum())
    explanation_payload = {
        "model_name": model_bundle["model_name"],
        "row_index": int(row_index),
        "customer_id": _json_safe(customer_id),
        "predicted_probability_churn": probability,
        "predicted_label": predicted_label,
        "predicted_class": predicted_class,
        "expected_model_output": base_value,
        "model_output_after_shap_contributions": shap_sum,
        "output_note": "For linear and tree explainers, SHAP values explain model output space; probability is reported separately.",
        "raw_customer_context": raw_context,
        "top_features_by_absolute_impact": _json_records(top_features),
        "top_features_increasing_churn_risk": _json_records(pd.DataFrame(positive_features)),
        "top_features_decreasing_churn_risk": _json_records(pd.DataFrame(negative_features)),
    }

    return explanation_payload, feature_contributions


def save_prediction_explanation(
    explanation_payload: dict[str, Any],
    feature_contributions: pd.DataFrame,
    json_path: str | Path = DEFAULT_PREDICTION_EXPLANATION_PATH,
    csv_path: str | Path = DEFAULT_PREDICTION_EXPLANATION_CSV_PATH,
    md_path: str | Path = DEFAULT_PREDICTION_EXPLANATION_MD_PATH,
) -> tuple[Path, Path, Path]:
    """Save the prediction explanation as JSON, CSV, and Markdown."""
    json_output_path = Path(json_path)
    csv_output_path = Path(csv_path)
    md_output_path = Path(md_path)
    json_output_path.parent.mkdir(parents=True, exist_ok=True)
    csv_output_path.parent.mkdir(parents=True, exist_ok=True)
    md_output_path.parent.mkdir(parents=True, exist_ok=True)

    json_output_path.write_text(json.dumps(explanation_payload, indent=2), encoding="utf-8")
    feature_contributions.to_csv(csv_output_path, index=False)
    md_output_path.write_text(_format_prediction_markdown(explanation_payload), encoding="utf-8")

    return json_output_path, csv_output_path, md_output_path


def run_shap_explainability(
    *,
    model_path: str | Path = DEFAULT_BEST_MODEL_PATH,
    data_path: str | Path = DEFAULT_DATA_PATH,
    output_dir: str | Path = DEFAULT_SHAP_OUTPUT_DIR,
    row_index: int | None = None,
    customer_id: str | None = None,
    background_size: int = 200,
    max_explain_rows: int = 1000,
    random_state: int = 42,
    max_display: int = 20,
) -> ShapArtifacts:
    """Generate SHAP plots and a prediction explanation for the best model."""
    output_path = Path(output_dir)
    summary_path = output_path / DEFAULT_SUMMARY_PLOT_PATH.name
    feature_importance_path = output_path / DEFAULT_FEATURE_IMPORTANCE_PATH.name
    waterfall_path = output_path / DEFAULT_WATERFALL_PLOT_PATH.name
    explanation_path = output_path / DEFAULT_PREDICTION_EXPLANATION_PATH.name
    explanation_csv_path = output_path / DEFAULT_PREDICTION_EXPLANATION_CSV_PATH.name
    explanation_md_path = output_path / DEFAULT_PREDICTION_EXPLANATION_MD_PATH.name

    model_bundle = load_model_bundle(model_path)
    explainability_data = prepare_explainability_data(model_bundle, data_path)
    model = model_bundle["model"]

    explainer, explanation, rows_to_explain = compute_shap_values(
        model,
        explainability_data.transformed_features,
        background_size=background_size,
        max_explain_rows=max_explain_rows,
        random_state=random_state,
    )

    summary_plot_path = save_summary_plot(
        explanation,
        rows_to_explain,
        summary_path,
        max_display=max_display,
    )
    feature_importance_plot_path = save_feature_importance_plot(
        explanation,
        rows_to_explain,
        feature_importance_path,
        max_display=max_display,
    )

    selected_row_index = choose_prediction_row(
        model,
        explainability_data.transformed_features,
        row_index=row_index,
        customer_id=customer_id,
        raw_data=explainability_data.raw_data,
    )
    waterfall_plot_path, row_explanation = save_waterfall_plot(
        explainer,
        explainability_data.transformed_features,
        selected_row_index,
        waterfall_path,
        max_display=max_display,
    )

    prediction_payload, feature_contributions = build_prediction_explanation(
        model_bundle,
        explainability_data,
        selected_row_index,
        row_explanation,
    )
    (
        prediction_explanation_path,
        prediction_explanation_csv_path,
        prediction_explanation_md_path,
    ) = save_prediction_explanation(
        prediction_payload,
        feature_contributions,
        explanation_path,
        explanation_csv_path,
        explanation_md_path,
    )

    return ShapArtifacts(
        summary_plot_path=summary_plot_path,
        feature_importance_plot_path=feature_importance_plot_path,
        waterfall_plot_path=waterfall_plot_path,
        prediction_explanation_path=prediction_explanation_path,
        prediction_explanation_csv_path=prediction_explanation_csv_path,
        prediction_explanation_md_path=prediction_explanation_md_path,
        selected_row_index=selected_row_index,
        selected_customer_id=prediction_payload["customer_id"],
        predicted_probability=prediction_payload["predicted_probability_churn"],
        predicted_label=prediction_payload["predicted_label"],
    )


def build_arg_parser() -> argparse.ArgumentParser:
    """Build command line arguments for SHAP explainability."""
    parser = argparse.ArgumentParser(description="Generate SHAP explanations for the churn model.")
    parser.add_argument("--model-path", default=str(DEFAULT_BEST_MODEL_PATH), help="Path to best model joblib bundle.")
    parser.add_argument("--data-path", default=str(DEFAULT_DATA_PATH), help="Path to the raw Telco churn CSV.")
    parser.add_argument("--output-dir", default=str(DEFAULT_SHAP_OUTPUT_DIR), help="Directory for SHAP outputs.")
    parser.add_argument("--row-index", type=int, default=None, help="Optional dataframe row index to explain.")
    parser.add_argument("--customer-id", default=None, help="Optional customerID to explain.")
    parser.add_argument("--background-size", type=int, default=200, help="SHAP background sample size.")
    parser.add_argument("--max-explain-rows", type=int, default=1000, help="Rows sampled for summary plots.")
    parser.add_argument("--random-state", type=int, default=42, help="Random seed for sampling.")
    parser.add_argument("--max-display", type=int, default=20, help="Maximum features shown in SHAP plots.")
    return parser


def print_explainability_summary(artifacts: ShapArtifacts) -> None:
    """Print generated SHAP artifact paths."""
    print(f"Selected row index: {artifacts.selected_row_index}")
    print(f"Selected customer ID: {artifacts.selected_customer_id}")
    print(f"Predicted label: {artifacts.predicted_label}")
    print(f"Predicted churn probability: {artifacts.predicted_probability:.4f}")
    print(f"SHAP summary plot: {artifacts.summary_plot_path.resolve()}")
    print(f"SHAP feature importance plot: {artifacts.feature_importance_plot_path.resolve()}")
    print(f"SHAP waterfall plot: {artifacts.waterfall_plot_path.resolve()}")
    print(f"Prediction explanation JSON: {artifacts.prediction_explanation_path.resolve()}")
    print(f"Prediction explanation CSV: {artifacts.prediction_explanation_csv_path.resolve()}")
    print(f"Prediction explanation Markdown: {artifacts.prediction_explanation_md_path.resolve()}")


def main(argv: list[str] | None = None) -> int:
    """Run SHAP explainability from the command line."""
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    artifacts = run_shap_explainability(
        model_path=args.model_path,
        data_path=args.data_path,
        output_dir=args.output_dir,
        row_index=args.row_index,
        customer_id=args.customer_id,
        background_size=args.background_size,
        max_explain_rows=args.max_explain_rows,
        random_state=args.random_state,
        max_display=args.max_display,
    )
    print_explainability_summary(artifacts)

    return 0


def _json_safe(value: Any) -> Any:
    """Convert numpy/pandas scalar values into JSON-safe Python values."""
    if pd.isna(value):
        return None
    if isinstance(value, np.generic):
        return value.item()
    return value


def _json_records(frame: pd.DataFrame) -> list[dict[str, Any]]:
    """Convert dataframe records into JSON-safe dictionaries."""
    records = frame.to_dict(orient="records")
    return [
        {key: _json_safe(value) for key, value in record.items()}
        for record in records
    ]


def _format_prediction_markdown(payload: dict[str, Any]) -> str:
    """Create a readable Markdown prediction explanation."""
    context_lines = [
        f"| {key} | {value} |"
        for key, value in payload["raw_customer_context"].items()
    ]
    feature_lines = [
        (
            f"| {record['feature']} | {record['direction']} | "
            f"{record['shap_value']:.4f} | {record['transformed_value']:.4f} |"
        )
        for record in payload["top_features_by_absolute_impact"]
    ]

    return "\n".join(
        [
            "# Prediction Explanation",
            "",
            f"Model: **{payload['model_name']}**",
            f"Customer ID: **{payload['customer_id']}**",
            f"Row index: **{payload['row_index']}**",
            f"Predicted label: **{payload['predicted_label']}**",
            f"Predicted churn probability: **{payload['predicted_probability_churn']:.2%}**",
            "",
            "Positive SHAP values increase churn risk. Negative SHAP values decrease churn risk.",
            "",
            "## Customer Context",
            "",
            "| Field | Value |",
            "| --- | --- |",
            *context_lines,
            "",
            "## Top Feature Contributions",
            "",
            "| Feature | Direction | SHAP value | Transformed value |",
            "| --- | --- | ---: | ---: |",
            *feature_lines,
            "",
            "## Model Output Note",
            "",
            payload["output_note"],
            "",
        ]
    )


if __name__ == "__main__":
    raise SystemExit(main())
